package mss.app.account;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "account")
public class Account {

	private String id;
	  private String firstName;
	  private String lastName;

	  public Account() {
	  }

	  @DynamoDBHashKey
	  @DynamoDBAutoGeneratedKey 
	  public String getId() {
		return id;
	  }

	  @DynamoDBAttribute
	  public String getFirstName() {
		return firstName;
	  }

	  @DynamoDBAttribute
	  public String getLastName() {
		return lastName;
	  }
	       
	  public void setId(String id) {
	    this.id = id;
	  }
	  
	  public void setFirstName(String firstName) {
	    this.firstName = firstName;
	  }

	  public void setLastName(String lastName) {
	    this.lastName = lastName;
	  }

	  @Override
	  public boolean equals(Object o) {
	      if (this == o) return true;
	      if (o == null || getClass() != o.getClass()) return false;

	      Account acct = (Account) o;

	      return id.equals(acct.id);
	  }

	  @Override
	  public int hashCode() {
	      return id.hashCode();
	  }	
	
}
