# Docker compose file for running config server
version: '3'
services:
  configserver:
    container_name: configserver
    image: philly2017/config-server
    ports:
      - "8888:8888"
    networks:
      - mtrnet

  configclient:
    container_name: configclient
    image: philly2017/configuration-client
    ports:
      - "8080:8080"
    environment:
#      - spring.cloud.config.uri=http://localhost:8888
      - spring.cloud.config.uri=http://configserver:8888
      - spring.cloud.config.failFast=true
      - spring.cloud.config.retry.max-attempts=30
      - spring.cloud.config.retry.max-interval=1500

    depends_on:
      - configserver
    command: dockerize -wait http://configserver:8888
    networks:
      - mtrnet

networks:
  mtrnet:
    driver: bridge
